# Generated by Django 2.2 on 2020-10-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('DNI', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('telefono', models.BigIntegerField()),
                ('direccion', models.CharField(max_length=40)),
            ],
        ),
    ]
