# Generated by Django 2.2 on 2020-10-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0002_categoria_divisa_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barrio', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='direccion',
        ),
    ]
