# Generated by Django 2.2 on 2020-11-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0004_auto_20201031_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, default='fotos_productos/default.png', upload_to='fotos_productos/'),
        ),
    ]
