# Generated by Django 2.2 on 2020-11-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0007_auto_20201103_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='DNI',
            new_name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(null=True),
        ),
    ]
