# Generated by Django 2.2 on 2020-11-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0007_auto_20201103_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='DNI',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
