# Generated by Django 2.2 on 2020-11-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0008_auto_20201104_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
    ]
