# Generated by Django 2.2 on 2020-11-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0009_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
