# Generated by Django 2.2 on 2020-11-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0010_producto_destacado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='destacado',
        ),
    ]
