# Generated by Django 2.2 on 2020-11-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0017_auto_20201125_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destacado',
        ),
    ]
