# Generated by Django 2.2 on 2020-11-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0018_delete_destacado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destacado',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, default=None, upload_to='fotos_destacados/')),
            ],
        ),
    ]
