# Generated by Django 2.2 on 2020-11-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0020_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destacado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
