# Generated by Django 2.2 on 2020-11-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0021_auto_20201126_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Divisa',
        ),
    ]
